[package]
name = "md_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
spider = { version = "=2.37.159", features = [
    "chrome",
    "chrome_intercept",
    "sitemap",
] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["rustls-tls"] }
